server:
  port: 8083

spring:
  application:
    name: ai-service

data:
  mongodb:
    database: fitness
    uri: mongodb://localhost:27017/fitness

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/